#!/bin/bash

# This line is just here so that output from tcpdump does not conflict with entering the password for sudo
# but it also serves as a good introduction to the script
sudo echo "Go Hummingbird!" >&2

# Determine the network interface
INTERFACE=$(echo $INTERFACE)
if [[ -z "${INTERFACE}" ]]; then
	if [[ "${OSTYPE}" == "linux-gnu" ]] || [[ "${OSTYPE}" == "linux-gnueabihf"  ]]; then
		INTERFACE=$(ip route get 8.8.8.8 | awk '{ print $(NF-2); exit }')
	elif [[ "${OSTYPE}" == "darwin"* ]]; then
		INTERFACE=$(route get 8.8.8.8 | grep interface | awk '{ print $NF; exit }')
	else
		echo "This script does not support this operating system. An override of INTERFACE is required." >&2
		exit 1
	fi
	export INTERFACE
fi

# Determine the local IP address
IP=$(ifconfig ${INTERFACE} | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')

# Send tcpdump output to stdout (redirected to Hummingbird)
# Ignore packets from the local IP address
# Before sending the packet header, pipe the output to sed to get just the src MAC address
sudo tcpdump -I -elt -i ${INTERFACE} not host ${IP} 2>> tcpdump_error.log | sed 's/ .*//'
